using System;
using System.Collections.Generic;

using Xamarin.Forms;

namespace Dissertation.Views.Graveyard
{
    public partial class TextblockTest : ContentPage
    {
        public TextblockTest()
        {
            InitializeComponent();

			string a = "Date: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINEDate: Sunday, 26 August 2018dsddsdsNEWLINELocation: dsdsadsadaNEWLINENEWLINEBench PressNEWLINENEWLINE0kg x 12NEWLINE0kg x 10NEWLINE0kg x 8NEWLINE0kg x 6NEWLINE0kg x 4NEWLINENEWLINENEWLINESquatNEWLINENEWLINE4.75kg x 16NEWLINENEWLINENEWLINE";

			string b = a.Replace("NEWLINE", "\n");

			//matt.Text = b;
        }
    }
}
